### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by SiliconExarch** [Speshkitty/DalamudPlugins#2]
I'd feel a lot more comfortable using this plugin if my character name and home server were hashed before being sent to the database.

**Comment by Speshkitty** [comment]
Fixed as of v1.4.0.0

**Comment by anon88391** [comment]
@Speshkitty 
1. Why do the database requests require the character name and the server? I see no logical reason for it, also hashing in this case is just security through obscurity since hashes are easily reversed with data like this.
2. Do you store user data?
3. Why not supply the database with the plugin to avoid handling user data altogether?
